// Roadmaps functionality
class RoadmapsManager {
  constructor() {
    this.filters = {
      difficulty: "all",
      duration: "all",
      category: "all",
    }
    this.roadmaps = []
    this.init()
  }

  init() {
    this.setupFilters()
    this.setupPreviewModals()
    this.loadRoadmaps()
    this.animateCards()
  }

  setupFilters() {
    document.querySelectorAll(".filter-btn").forEach((btn) => {
      btn.addEventListener("click", (e) => {
        const filterType = e.target.dataset.type
        const filterValue = e.target.dataset.filter

        // Update active state
        document.querySelectorAll(`[data-type="${filterType}"]`).forEach((b) => b.classList.remove("active"))
        e.target.classList.add("active")

        // Update filter
        this.filters[filterType] = filterValue
        this.applyFilters()
      })
    })
  }

  setupPreviewModals() {
    const modal = document.getElementById("previewModal")
    const modalClose = document.getElementById("modalClose")
    const modalClose2 = document.getElementById("modalClose2")

    // Preview buttons
    document.querySelectorAll(".preview-btn").forEach((btn) => {
      btn.addEventListener("click", (e) => {
        const roadmapId = e.target.dataset.roadmap
        this.showPreview(roadmapId)
      })
    })

    // Close modal
    modalClose.addEventListener("click", () => this.closeModal())
    modalClose2.addEventListener("click", () => this.closeModal())
    modal.addEventListener("click", (e) => {
      if (e.target === modal) this.closeModal()
    })

    // Escape key
    document.addEventListener("keydown", (e) => {
      if (e.key === "Escape") this.closeModal()
    })
  }

  async loadRoadmaps() {
    const storedRoadmap = localStorage.getItem("roadmap");
    if (storedRoadmap) {
        const steps = JSON.parse(storedRoadmap);
        this.displayRoadmap(steps);
    } else {
        // If not in localStorage, try fetching from the server
        try {
            const response = await fetch("/roadmap/user"); // Assumes a session or default user
            if (response.ok) {
                const data = await response.json();
                if (data.steps && data.steps.length > 0) {
                    localStorage.setItem("roadmap", JSON.stringify(data.steps));
                    this.displayRoadmap(data.steps);
                } else {
                    this.roadmaps = [];
                    this.renderRoadmaps();
                }
            } else {
                this.roadmaps = [];
                this.renderRoadmaps();
            }
        } catch (error) {
            console.error("Error fetching roadmap:", error);
            this.roadmaps = [];
            this.renderRoadmaps();
        }
    }
    window.addEventListener("storage", () => this.loadRoadmaps());
}

displayRoadmap(steps) {
    this.roadmaps = [{
        id: "custom",
        title: "Your Custom Roadmap",
        icon: "🚀",
        difficulty: "custom",
        duration: "custom",
        category: "custom",
        description: "A personalized roadmap generated by the AI assistant.",
        modules: steps.map((step, index) => ({
            title: `Step ${index + 1}: ${step.title}`,
            description: step.advice,
        })),
    }, ];
    this.renderRoadmaps();
}

  renderRoadmaps() {
    const container = document.querySelector(".roadmap-grid")
    container.innerHTML = "" // Clear existing roadmaps

    if (this.roadmaps.length === 0) {
      container.innerHTML = `<p>No roadmaps available. Go to the chat to create one!</p>`
      return
    }

    this.roadmaps.forEach((roadmap) => {
      const card = document.createElement("div")
      card.className = "roadmap-card"
      card.dataset.difficulty = roadmap.difficulty
      card.dataset.duration = roadmap.duration
      card.dataset.category = roadmap.category
      card.innerHTML = `
        <div class="card-header">
          <div class="card-icon">${roadmap.icon}</div>
          <h3 class="card-title">${roadmap.title}</h3>
        </div>
        <p class="card-description">${roadmap.description}</p>
        <div class="card-progress">
          <div class="progress-bar">
            <div class="progress-fill" style="width: 0%;"></div>
          </div>
          <span>0% Complete</span>
        </div>
        <div class="card-footer">
          <button class="preview-btn" data-roadmap="${roadmap.id}">Preview</button>
          <a href="careers.html?path=${roadmap.id}" class="start-btn">Start Learning</a>
        </div>
      `
      container.appendChild(card)
    })

    this.setupPreviewModals() // Re-initialize modals for new cards
    this.animateCards()
  }

  applyFilters() {
    const cards = document.querySelectorAll(".roadmap-card")

    cards.forEach((card) => {
      const difficulty = card.dataset.difficulty
      const duration = card.dataset.duration
      const category = card.dataset.category

      const matchesDifficulty = this.filters.difficulty === "all" || difficulty === this.filters.difficulty
      const matchesDuration = this.filters.duration === "all" || duration === this.filters.duration
      const matchesCategory = this.filters.category === "all" || category === this.filters.category

      if (matchesDifficulty && matchesDuration && matchesCategory) {
        card.classList.remove("hidden")
        card.style.animation = "fadeInUp 0.6s ease-out"
      } else {
        card.classList.add("hidden")
      }
    })
  }

  showPreview(roadmapId) {
    const roadmap = this.roadmaps.find((r) => r.id === roadmapId)
    if (!roadmap) return

    const modal = document.getElementById("previewModal")
    const modalTitle = document.getElementById("modalTitle")
    const modalBody = document.getElementById("modalBody")
    const modalStart = document.getElementById("modalStart")

    modalTitle.textContent = `${roadmap.title} - Preview`
    modalStart.href = `careers.html?path=${roadmapId}`

    modalBody.innerHTML = `
      <div class="roadmap-preview">
        <div class="preview-header">
          <div class="preview-icon">${roadmap.icon}</div>
          <h3 class="preview-title">${roadmap.title}</h3>
          <p class="preview-description">${roadmap.description}</p>
        </div>
        <div class="preview-modules">
          <h4 style="margin-bottom: 1rem; color: var(--foreground);">Learning Modules</h4>
          ${roadmap.modules
            .map(
              (module, index) => `
            <div class="module-item">
              <div class="module-number">${index + 1}</div>
              <div class="module-content">
                <h4>${module.title}</h4>
                <p>${module.description}</p>
              </div>
            </div>
          `,
            )
            .join("")}
        </div>
      </div>
    `

    modal.classList.add("active")
    document.body.style.overflow = "hidden"
  }

  closeModal() {
    const modal = document.getElementById("previewModal")
    modal.classList.remove("active")
    document.body.style.overflow = "auto"
  }

  animateCards() {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.style.animation = "fadeInUp 0.6s ease-out"
          }
        })
      },
      { threshold: 0.1 },
    )

    document.querySelectorAll(".roadmap-card").forEach((card) => {
      observer.observe(card)
    })
  }
}

// Initialize when DOM is loaded
document.addEventListener("DOMContentLoaded", () => {
  new RoadmapsManager()
})

// Add some interactive effects
document.addEventListener("DOMContentLoaded", () => {
  // Animate progress bars on scroll
  const progressBars = document.querySelectorAll(".progress-fill")
  const progressObserver = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          const width = entry.target.style.width
          entry.target.style.width = "0%"
          setTimeout(() => {
            entry.target.style.width = width
          }, 200)
        }
      })
    },
    { threshold: 0.5 },
  )

  progressBars.forEach((bar) => {
    progressObserver.observe(bar)
  })

  // Add hover effects to roadmap cards
  document.querySelectorAll(".roadmap-card").forEach((card) => {
    card.addEventListener("mouseenter", function () {
      this.style.transform = "translateY(-15px) scale(1.02)"
    })

    card.addEventListener("mouseleave", function () {
      this.style.transform = "translateY(0) scale(1)"
    })
  })

  // Animate filter buttons
  document.querySelectorAll(".filter-btn").forEach((btn) => {
    btn.addEventListener("click", function () {
      this.style.transform = "scale(0.95)"
      setTimeout(() => {
        this.style.transform = "scale(1)"
      }, 150)
    })
  })
})
